/*
 * Todolist RESTful API
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: ikoafianando123@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
