/*
 * Todolist RESTful API
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: ikoafianando123@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ArrayTodolist;
import io.swagger.client.model.CreateOrUpdateTodolist;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.Todolist;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TodolistApi
 */
@Ignore
public class TodolistApiTest {

    private final TodolistApi api = new TodolistApi();

    /**
     * Get All Todolist
     *
     * Get all todolist by default
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todolistGetTest() throws Exception {
        Boolean includeDone = null;
        String name = null;
        ArrayTodolist response = api.todolistGet(includeDone, name);

        // TODO: test validations
    }
    /**
     * Create New Todolist
     *
     * Create new todolist to database
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todolistPostTest() throws Exception {
        CreateOrUpdateTodolist body = null;
        Todolist response = api.todolistPost(body);

        // TODO: test validations
    }
    /**
     * Delete existing Todolist
     *
     * Delete existing todolist in database
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todollistTodolistIdDeleteTest() throws Exception {
        String todolistId = null;
        InlineResponse200 response = api.todollistTodolistIdDelete(todolistId);

        // TODO: test validations
    }
    /**
     * Update existing Todolist
     *
     * Update existing todolist in database
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todollistTodolistIdPutTest() throws Exception {
        CreateOrUpdateTodolist body = null;
        String todolistId = null;
        Todolist response = api.todollistTodolistIdPut(body, todolistId);

        // TODO: test validations
    }
}
